kind = "web"
previewPath = "/"
title = "iROC GmbH"
version = "1.0.0"
id = "artifacts/iroc-website"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18856

[services.development]
run = "pnpm --filter @workspace/iroc-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/iroc-website", "run", "build" ]
serve = "static"
publicDir = "artifacts/iroc-website/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18856"
BASE_PATH = "/"
