import { Router, type IRouter } from "express";
import healthRouter from "./health";
import customersRouter from "./customers";
import ordersRouter from "./orders";
import trainingRouter from "./training";
import authRouter from "./auth";
import doctorsRouter from "./doctors";
import resourcesRouter from "./resources";
import adminRouter from "./admin";
import teamRouter from "./team";
import storageRouter from "./storage";
import settingsRouter from "./settings";
import eventsRouter from "./events";
import contactRouter from "./contact";
import patientMediaRouter from "./patient-media";
import patientExtrasRouter from "./patient-extras";
import patientTestimonialsRouter from "./patient-testimonials";
import irocRouter from "./iroc";
import datevRouter from "./datev";
import congressRouter from "./congress";
import agentRouter from "./agent";
import toriRouter from "./tori";
import contentRouter from "./content";
import { geminiRouter } from "./gemini";
import sallyRouter from "./sally";
import expensesRouter from "./expenses";
import portalRouter from "./portal";
import spiroRouter from "./spiro";
import { adminAuthRouter } from "./admin-auth";

const router: IRouter = Router();

router.use(contentRouter);
router.use(patientExtrasRouter);
router.use(patientTestimonialsRouter);
router.use(patientMediaRouter);
router.use(healthRouter);
router.use(customersRouter);
router.use(ordersRouter);
router.use(trainingRouter);
router.use(authRouter);
router.use(doctorsRouter);
router.use(resourcesRouter);
router.use(adminRouter);
router.use(teamRouter);
router.use(storageRouter);
router.use(settingsRouter);
router.use(eventsRouter);
router.use(contactRouter);
router.use(irocRouter);
router.use(datevRouter);
router.use(expensesRouter);
router.use(congressRouter);
router.use(agentRouter);
router.use(toriRouter);
router.use(geminiRouter);
router.use(sallyRouter);
router.use(expensesRouter);
router.use(portalRouter);
router.use(spiroRouter);
router.use(adminAuthRouter);

export default router;
