// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cert-designs/MiniStemDE.tsx": () => import("../components/mockups/cert-designs/MiniStemDE.tsx"),
  "./components/mockups/cert-designs/MiniStemEN.tsx": () => import("../components/mockups/cert-designs/MiniStemEN.tsx"),
  "./components/mockups/cert-designs/Modern.tsx": () => import("../components/mockups/cert-designs/Modern.tsx"),
  "./components/mockups/cert-designs/Premium.tsx": () => import("../components/mockups/cert-designs/Premium.tsx"),
  "./components/mockups/cert-designs/Prestige.tsx": () => import("../components/mockups/cert-designs/Prestige.tsx"),
  "./components/mockups/cert-designs/SpirecutEN.tsx": () => import("../components/mockups/cert-designs/SpirecutEN.tsx"),
  "./components/mockups/invoice-designs/CommercialInvoice.tsx": () => import("../components/mockups/invoice-designs/CommercialInvoice.tsx"),
  "./components/mockups/invoice-designs/InvoiceAnnotation.tsx": () => import("../components/mockups/invoice-designs/InvoiceAnnotation.tsx"),
  "./components/mockups/invoice-designs/StandardInvoice.tsx": () => import("../components/mockups/invoice-designs/StandardInvoice.tsx"),
  "./components/mockups/iroc-dashboard/Current.tsx": () => import("../components/mockups/iroc-dashboard/Current.tsx"),
  "./components/mockups/report-print/PrintCustomers.tsx": () => import("../components/mockups/report-print/PrintCustomers.tsx"),
  "./components/mockups/report-print/PrintInventory.tsx": () => import("../components/mockups/report-print/PrintInventory.tsx"),
  "./components/mockups/report-print/PrintInventoryNoSectionTitle.tsx": () => import("../components/mockups/report-print/PrintInventoryNoSectionTitle.tsx"),
  "./components/mockups/report-print/PrintLeads.tsx": () => import("../components/mockups/report-print/PrintLeads.tsx"),
  "./components/mockups/report-print/PrintSales.tsx": () => import("../components/mockups/report-print/PrintSales.tsx"),
  "./components/mockups/report-print/PrintTopProducts.tsx": () => import("../components/mockups/report-print/PrintTopProducts.tsx"),
  "./components/mockups/spirecut-app-shell/AppLike.tsx": () => import("../components/mockups/spirecut-app-shell/AppLike.tsx"),
  "./components/mockups/spirecut-app-shell/Current.tsx": () => import("../components/mockups/spirecut-app-shell/Current.tsx")
};
