export const MICROSOFT_MAILBOX_ROLES = [
  {
    value: "general",
    labelDe: "Allgemeine Kommunikation",
    labelEn: "General communication",
    addressDe: "info@i-roc.de",
    addressEn: "info@i-roc.de",
    functionDe: "Zentrale Standardadresse für allgemeine iROC-Kommunikation, Fallbacks und Benachrichtigungen.",
    functionEn: "Main default address for general iROC communication, fallbacks, and notifications.",
    pathDe: "E-Mail-Konfiguration → Microsoft 365 → Verwendungszweck",
    pathEn: "Email Configuration → Microsoft 365 → Purpose",
    settingDe: "Standard / Fallback",
    settingEn: "Default / fallback",
  },
  {
    value: "website_contact",
    labelDe: "Website – Kontaktformular",
    labelEn: "Website — Contact form",
    addressDe: "info@i-roc.de · info@spirecut.de · info@spirecut.com",
    addressEn: "info@i-roc.de · info@spirecut.de · info@spirecut.com",
    functionDe: "Postfach für neue Kontaktanfragen von iROC und Spirecut.",
    functionEn: "Mailbox for new contact enquiries from iROC and Spirecut.",
    pathDe: "Konfiguration → Website → iROC Website → E-Mail-Adressen",
    pathEn: "Configuration → Website → iROC Website → Email Addresses",
    settingDe: "ws_contact_email · sp_contact_email_de · sp_contact_email_com",
    settingEn: "ws_contact_email · sp_contact_email_de · sp_contact_email_com",
  },
  {
    value: "order_new",
    labelDe: "Bestellungen – Neukunden",
    labelEn: "Orders — New customers",
    addressDe: "Konfigurierbare interne Empfängeradresse",
    addressEn: "Configurable internal recipient address",
    functionDe: "Interne Benachrichtigung bei einer Registrierung oder Bestellung eines Neukunden.",
    functionEn: "Internal notification when a new customer registers or places an order.",
    pathDe: "Konfiguration → Website → iROC Website → E-Mail-Adressen",
    pathEn: "Configuration → Website → iROC Website → Email Addresses",
    settingDe: "email_dest_order_new",
    settingEn: "email_dest_order_new",
  },
  {
    value: "order_existing",
    labelDe: "Bestellungen – Bestandskunden",
    labelEn: "Orders — Existing customers",
    addressDe: "Konfigurierbare interne Empfängeradresse",
    addressEn: "Configurable internal recipient address",
    functionDe: "Interne Benachrichtigung bei einer Bestellung eines bestehenden Kunden.",
    functionEn: "Internal notification when an existing customer places an order.",
    pathDe: "Konfiguration → Website → iROC Website → E-Mail-Adressen",
    pathEn: "Configuration → Website → iROC Website → Email Addresses",
    settingDe: "email_dest_order_existing",
    settingEn: "email_dest_order_existing",
  },
  {
    value: "training_spirecut",
    labelDe: "Schulungen – Spirecut®",
    labelEn: "Training — Spirecut®",
    addressDe: "Konfigurierbare interne Empfängeradresse",
    addressEn: "Configurable internal recipient address",
    functionDe: "Empfänger für Spirecut®-Schulungsanmeldungen.",
    functionEn: "Recipient for Spirecut® training registrations.",
    pathDe: "Konfiguration → Website → iROC Website → E-Mail-Adressen",
    pathEn: "Configuration → Website → iROC Website → Email Addresses",
    settingDe: "email_dest_training_spirecut",
    settingEn: "email_dest_training_spirecut",
  },
  {
    value: "training_ministem",
    labelDe: "Schulungen – MiniStem®",
    labelEn: "Training — MiniStem®",
    addressDe: "Konfigurierbare interne Empfängeradresse",
    addressEn: "Configurable internal recipient address",
    functionDe: "Empfänger für MiniStem®-Schulungsanmeldungen.",
    functionEn: "Recipient for MiniStem® training registrations.",
    pathDe: "Konfiguration → Website → iROC Website → E-Mail-Adressen",
    pathEn: "Configuration → Website → iROC Website → Email Addresses",
    settingDe: "email_dest_training_ministem",
    settingEn: "email_dest_training_ministem",
  },
  {
    value: "invoice",
    labelDe: "Rechnungen – Versand/Kontakt",
    labelEn: "Invoices — Sending/contact",
    addressDe: "Kundenadresse aus dem Rechnungsdatensatz",
    addressEn: "Customer address from the invoice record",
    functionDe: "Absender- oder Kontaktpostfach für Rechnungen; die Rechnung selbst geht an den jeweiligen Kunden.",
    functionEn: "Sender or contact mailbox for invoices; the invoice itself goes to the relevant customer.",
    pathDe: "Rechnung → Senden · E-Mail-Konfiguration → Microsoft 365",
    pathEn: "Invoice → Send · Email Configuration → Microsoft 365",
    settingDe: "invoice_contact_email",
    settingEn: "invoice_contact_email",
  },
  {
    value: "invoice_ai",
    labelDe: "KI-Rechnungseingang",
    labelEn: "AI invoice processing",
    addressDe: "e.manos@i-roc.de",
    addressEn: "e.manos@i-roc.de",
    functionDe: "Microsoft-365-Postfach, aus dem Tori/Sally eingehende Rechnungsdokumente lesen und analysieren kann.",
    functionEn: "Microsoft 365 mailbox from which Tori/Sally can read and analyze incoming invoice documents.",
    pathDe: "E-Mail-Konfiguration → Microsoft 365 → KI-Rechnungseingang",
    pathEn: "Email Configuration → Microsoft 365 → AI invoice processing",
    settingDe: "Postfachzweck invoice_ai",
    settingEn: "Mailbox purpose invoice_ai",
  },
  {
    value: "datev",
    labelDe: "DATEV / Buchhaltung",
    labelEn: "DATEV / bookkeeping",
    addressDe: "Beim DATEV-Export angegebene Buchhaltungsadresse",
    addressEn: "Bookkeeping address entered during DATEV export",
    functionDe: "Empfänger der per E-Mail versendeten DATEV-Exporte.",
    functionEn: "Recipient of DATEV exports sent by email.",
    pathDe: "Finance → DATEV-Export · E-Mail-Konfiguration → Microsoft 365",
    pathEn: "Finance → DATEV Export · Email Configuration → Microsoft 365",
    settingDe: "datev_bookkeeper_email",
    settingEn: "datev_bookkeeper_email",
  },
  {
    value: "announcement",
    labelDe: "Ankündigungen",
    labelEn: "Announcements",
    addressDe: "info@i-roc.de oder separate Absenderadresse",
    addressEn: "info@i-roc.de or a separate sender address",
    functionDe: "Absender für Ankündigungs-E-Mails an Ärzte und Geschäftskontakte.",
    functionEn: "Sender for announcement emails to doctors and business contacts.",
    pathDe: "Konfiguration → Website → iROC Website → E-Mail-Adressen",
    pathEn: "Configuration → Website → iROC Website → Email Addresses",
    settingDe: "iroc_announcement_from",
    settingEn: "iroc_announcement_from",
  },
  {
    value: "smtp",
    labelDe: "SMTP / ausgehender Versand",
    labelEn: "SMTP / outgoing sending",
    addressDe: "e.manos@i-roc.de oder das gewünschte Microsoft-Postfach",
    addressEn: "e.manos@i-roc.de or the desired Microsoft mailbox",
    functionDe: "Identität für den allgemeinen ausgehenden Versand. SMTP-Zugangsdaten werden weiterhin separat im SMTP-Bereich verwaltet.",
    functionEn: "Identity for general outgoing sending. SMTP credentials are still managed separately in the SMTP section.",
    pathDe: "E-Mail-Konfiguration → Microsoft 365 und → SMTP",
    pathEn: "Email Configuration → Microsoft 365 and → SMTP",
    settingDe: "smtp_user · smtp_from",
    settingEn: "smtp_user · smtp_from",
  },
  {
    value: "tori_ai",
    labelDe: "Tori KI-Dokumentenanalyse",
    labelEn: "Tori AI document analysis",
    addressDe: "Eigenes Tori-Postfach, z. B. tori@i-roc.de",
    addressEn: "Dedicated Tori mailbox, e.g. tori@i-roc.de",
    functionDe: "Postfach für den späteren nächtlichen Dokumentenimport und die Analyse von Rechnungs- und Ausgabenanhängen.",
    functionEn: "Mailbox for the planned nightly document import and analysis of invoice and expense attachments.",
    pathDe: "Agents/Managers → Tori · E-Mail-Konfiguration → Microsoft 365",
    pathEn: "Agents/Managers → Tori · Email Configuration → Microsoft 365",
    settingDe: "Postfachzweck tori_ai",
    settingEn: "Mailbox purpose tori_ai",
  },
  {
    value: "sally_ai",
    labelDe: "Sally KI-Agentin",
    labelEn: "Sally AI agent",
    addressDe: "sales@i-roc.de",
    addressEn: "sales@i-roc.de",
    functionDe: "Microsoft-365-Postfach für Sallys CRM-Kommunikation und freizugebende E-Mails.",
    functionEn: "Microsoft 365 mailbox for Sally CRM communication and emails awaiting approval.",
    pathDe: "Agents/Managers → Sally · E-Mail-Konfiguration → Microsoft 365",
    pathEn: "Agents/Managers → Sally · Email Configuration → Microsoft 365",
    settingDe: "Sally-Postfachzweck sally_ai",
    settingEn: "Sally mailbox purpose sally_ai",
  },
  {
    value: "notifications",
    labelDe: "Sonstige Benachrichtigungen",
    labelEn: "Other notifications",
    addressDe: "info@i-roc.de oder separate Benachrichtigungsadresse",
    addressEn: "info@i-roc.de or a separate notification address",
    functionDe: "Interne System- und Statusbenachrichtigungen, die keiner spezielleren Rolle zugeordnet sind.",
    functionEn: "Internal system and status notifications that do not belong to a more specific role.",
    pathDe: "E-Mail-Konfiguration → Microsoft 365 → Benachrichtigungen",
    pathEn: "Email Configuration → Microsoft 365 → Notifications",
    settingDe: "notifications",
    settingEn: "notifications",
  },
] as const;

export type MicrosoftMailboxPurpose = (typeof MICROSOFT_MAILBOX_ROLES)[number]["value"];